### ISSUE TITLE
residuals()

### ISSUE THREAD

**Issue by shaobo-li** [XiaoruiZhu/PAsso#4]
`data("ANES2016")`
`fit.PID1<- polr(as.factor(PID)~age+edu.year+income.num, data=ANES2016, method="probit")`
`fit.PID2<- vglm(as.numeric(PID)~age+edu.year+income.num, data=ANES2016, family=acat(reverse=TRUE, parallel=TRUE))`
`r1<- residuals(fit.PID2, jitter="uniform",jitter.uniform.scale="response", nsim=30)`
`r2<- residuals(fit.PID2, jitter="uniform",jitter.uniform.scale="probability", nsim=30)`
`attr(r1,"draws")[,1]`

**the use of attr() is extremely inconvenient to get a simple output. Suggest to use more traditional way, e.g., r1[,1]**
**5th line, r2<-... does not work even if fit.PID2 is adjacent category logit model...**

**Comment by XiaoruiZhu** [comment]
Close issue. See Fix issue #4 commit.
